# 实验一 spotify-2023.csv数据预处理
## 1. 数据集用途
- 音乐分析
- 平台对比
- 艺术家影响力
- 时间趋势
- 跨平台存在

## 2. 导入需要用到的包

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

## 3. 读取数据集

In [2]:
# 读取数据集，文件在当前目录下，文件地址即文件名
spotify = pd.read_csv('spotify-2023.csv', encoding = 'latin-1')

## 4. 检查数据集基本信息

In [3]:
spotify

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [4]:
# 输出前5行数据
spotify.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [5]:
# 获取数据集中的列名
spotify.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [6]:
# 查看数据集各列基本信息
spotify.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [7]:
# 查看数值变量的描述性统计信息
spotify.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [8]:
# 查看数据类型为object的变量的描述性统计信息
spotify.describe(include = 'object')

,track_name,artist(s)_name,streams,in_deezer_playlists,in_shazam_charts,key,mode
count,953,953,953,953,903,858,953
unique,943,645,949,348,198,11,2
top,Daylight,Taylor Swift,723894473,0,0,C#,Major
freq,2,34,2,24,344,120,550

In [9]:
# 检查有无重复行
spotify.duplicated().sum()

0

In [10]:
# 获取各列缺失值的汇总计数
missing_values = spotify.isnull().sum()
missing_values

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

经过上述操作，分析输出结果有以下发现和思考：
1. 'in_shazam_charts', 'key'列分别存在50个和95个缺失值，这两列都是重要数据，分别可以用于平台分析和音乐分析，需要考虑处理方法：前者的数据表示在榜单中的存在以及排名，由于观察到'in_apple_charts','in_deezer_charts'列中有最小值 0， 合理推测0用来表示未上榜，故该列缺失值考虑用0来代替；后者为音乐的调性，无法从其他数据中推测和估计，但与音乐属性特征相关的数据仅用于音乐分析，考虑对该列不缺失的行进行子数据集提取用于音乐分析，而后在用于其他分析的新数据集中删除其他存储了音乐属性特征数据的列。
2. 'artist_count'在后续分析中不会用到，是冗余数据
3. 在艺术家分析中考虑将共同创作一个作品的多个艺术家视为一个组合，而不考虑对'artist_name'拆分以及如何计算不同艺术家对同一作品的贡献比重
4. 每一行代表一个track即一首音乐，原数据集只有'track_name'作为每一行的标识，在后续分析中可能需要对其进行编码得到'track_id'
5. 'streams','in_deezer_playlists','in_shazam_charts'应当是数值数据被读取为对象数据，应转化数据类型
6. 有关发布时间的数据被分为三列'released_year','released_month','released_day'， 且被读取成int64数值型数据，但在后续时间趋势分析中，我们需要日期数据以进行时间序列分析，应转化数据类型
7. 通过观察描述性统计信息未发现明显异常值，例如：应该是整数的数据中存在浮点数，单位是百分比的列包含负数或有值大于100
8. 原数据集中不存在重复行
9. 'key'与'mode'都代表没有顺序、非数值的类别，很容易想到对其使用独热编码以便后续分析
10. 为方便后续用到'streams'数据的分析、比较、可视化等操作，考虑采用Min-Max标准化方法将其标准化

## 5. 为数据集编码
'track_name'可能重复，但只要没有重复行，就认为每一行都是不同的track，因此不仅对'track_name'的唯一值赋予'track_id',而是考虑对原数据集中所有行按照索引赋予id，由于索引与行本来就唯一对应，因此不需要特别存储'track_id'与每条数据的对应关系。

In [11]:
# 打印原数据集已有的索引，如果索引异常需要重设
spotify.index

RangeIndex(start=0, stop=953, step=1)

In [12]:
# 将索引存储到track_id列中作为每一行数据的独特编码
spotify['track_id'] = spotify.index

In [13]:
# 查看改动后数据集前5行
spotify.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,track_id
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,0
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,1
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,2
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,A,Major,55,58,72,11,0,11,15,3
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,4

## 6. 获取用于音乐分析的数据集
- 将'streams'转化为数值型变量并进行Min-Max标准化
- 提取列'track_id', 'streams','bpm', 'key', 'mode', 'danceability_%', 'valence_%','energy_%', 'acousticness_%', 'instrumentalness_%', 'liveness_%','speechiness_%'
- 删除'key'缺失数据的行
- 对'key', 'mode'列进行独热编码
- 导出处理完毕的用于音乐分析的数据集

In [14]:
# spotify['streams'] = pd.to_numeric(spotify['streams'])
# 试转化数据类型为数值，但上述代码会发生报错，报错信息提示position 574处有无法转化为数值的字符串
# 删除该行，并重新转化
spotify.drop([574], inplace = True)
spotify['streams'] = pd.to_numeric(spotify['streams'])

In [15]:
# 对新获得的'streams'数据进行Min-Max标准化
# 保存、训练和使用scaler标准化数据
scaler = MinMaxScaler()
spotify['streams'] = scaler.fit_transform(spotify[['streams']])

# 查看改动后数据集前5行
spotify.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,track_id
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,0.038170,43,...,B,Major,80,89,83,31,0,8,4,0
1,LALA,Myke Towers,1,2023,3,23,1474,48,0.036101,48,...,C#,Major,71,61,74,7,0,10,4,1
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,0.037798,94,...,F,Major,51,32,53,17,0,31,6,2
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,0.216215,116,...,A,Major,55,58,72,11,0,11,15,3
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,0.081869,84,...,A,Minor,65,23,80,14,63,11,6,4

In [16]:
# 提取音乐分析所需的列到新数据集spotify_features
spotify_features = spotify[['track_id', 'streams','bpm', 'key', 'mode', 'danceability_%', 'valence_%','energy_%', 'acousticness_%', 'instrumentalness_%', 'liveness_%','speechiness_%']]
# 查看新数据集前5行
spotify_features

,track_id,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,0,0.038170,125,B,Major,80,89,83,31,0,8,4
1,1,0.036101,92,C#,Major,71,61,74,7,0,10,4
2,2,0.037798,138,F,Major,51,32,53,17,0,31,6
3,3,0.216215,170,A,Major,55,58,72,11,0,11,15
4,4,0.081869,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...
948,948,0.024696,144,A,Major,60,24,39,57,0,8,3
949,949,0.032903,166,F#,Major,42,7,24,83,1,12,6
950,950,0.019847,92,C#,Major,80,81,67,4,0,8,6
951,951,0.036149,97,C#,Major,82,67,77,8,0,12,5
952,952,0.025920,90,E,Minor,61,32,67,15,0,11,5

In [17]:
# 删除'key'缺失的行
spotify_features.dropna(subset = 'key')

,track_id,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,0,0.038170,125,B,Major,80,89,83,31,0,8,4
1,1,0.036101,92,C#,Major,71,61,74,7,0,10,4
2,2,0.037798,138,F,Major,51,32,53,17,0,31,6
3,3,0.216215,170,A,Major,55,58,72,11,0,11,15
4,4,0.081869,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...
948,948,0.024696,144,A,Major,60,24,39,57,0,8,3
949,949,0.032903,166,F#,Major,42,7,24,83,1,12,6
950,950,0.019847,92,C#,Major,80,81,67,4,0,8,6
951,951,0.036149,97,C#,Major,82,67,77,8,0,12,5
952,952,0.025920,90,E,Minor,61,32,67,15,0,11,5

In [18]:
# 将'key', 'mode'进行独热编码
spotify_features = pd.get_dummies(spotify_features, columns = ['key', 'mode'])

In [19]:
# 查看改动后数据集的前5行
spotify_features.head()

,track_id,streams,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,...,key_C#,key_D,key_D#,key_E,key_F,key_F#,key_G,key_G#,mode_Major,mode_Minor
0,0,0.038170,125,80,89,83,31,0,8,4,...,False,False,False,False,False,False,False,False,True,False
1,1,0.036101,92,71,61,74,7,0,10,4,...,True,False,False,False,False,False,False,False,True,False
2,2,0.037798,138,51,32,53,17,0,31,6,...,False,False,False,False,True,False,False,False,True,False
3,3,0.216215,170,55,58,72,11,0,11,15,...,False,False,False,False,False,False,False,False,True,False
4,4,0.081869,144,65,23,80,14,63,11,6,...,False,False,False,False,False,False,False,False,False,True

In [20]:
# 存储处理完毕的用于音乐分析的数据集
spotify_features.to_csv('spotify_features.csv', index= False)

## 7. 获取用于其他后续分析的数据集
- 删除只用于音乐分析的列和冗余的'artist_count'列
- 将'released_year','released_month','released_day'转化为日期数据
- 将'in_deezer_playlists','in_shazam_charts'数据类型转化为数值，并用0替代缺失值

In [21]:
# 按列名删除不需要的列并存储到新数据集
spotify_else = spotify.drop(['artist_count', 'bpm', 'key', 'mode', 'danceability_%', 'valence_%','energy_%', 'acousticness_%', 'instrumentalness_%', 'liveness_%','speechiness_%'], axis = 1)
# 查看提取数据集的前5行
spotify_else.head()

,track_name,artist(s)_name,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,track_id
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2023,7,14,553,147,0.038170,43,263,45,10,826,0
1,LALA,Myke Towers,2023,3,23,1474,48,0.036101,48,126,58,14,382,1
2,vampire,Olivia Rodrigo,2023,6,30,1397,113,0.037798,94,207,91,14,949,2
3,Cruel Summer,Taylor Swift,2019,8,23,7858,100,0.216215,116,207,125,12,548,3
4,WHERE SHE GOES,Bad Bunny,2023,5,18,3133,50,0.081869,84,133,87,15,425,4

In [22]:
# 获取日期数据，并存储为'date'列
# spotify_else['date'] = pd.to_datetime(spotify_else[['released_year','released_month', 'released_day']])
# 尝试上述函数后发现报错，to_datatime函数不能找到需要的年月日数据，故改用连接字符串格式的年月日数据再转化
spotify_else['date'] = pd.to_datetime(spotify_else['released_year'].astype(str) + '-' + spotify_else['released_month'].astype(str) + '-' + spotify_else['released_day'].astype(str))
# 删除原来的年月日列
spotify_else.drop(['released_year', 'released_month', 'released_day'], axis = 1, inplace = True)
# 查看改动后数据集前5行
spotify_else.head()

,track_name,artist(s)_name,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,track_id,date
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",553,147,0.038170,43,263,45,10,826,0,2023-07-14
1,LALA,Myke Towers,1474,48,0.036101,48,126,58,14,382,1,2023-03-23
2,vampire,Olivia Rodrigo,1397,113,0.037798,94,207,91,14,949,2,2023-06-30
3,Cruel Summer,Taylor Swift,7858,100,0.216215,116,207,125,12,548,3,2019-08-23
4,WHERE SHE GOES,Bad Bunny,3133,50,0.081869,84,133,87,15,425,4,2023-05-18

In [23]:
# 转化'in_deezer_playlists','in_shazam_charts'数据类型转化为数值
# 'in_deezer_playlists'无缺失值，直接转化
# spotify_else['in_deezer_playlists'] = pd.to_numeric(spotify_else['in_deezer_playlists'])
# 首次运行会报错，报错信息指出在position 48 的数据中有异常','
# 删除该列中的',', 再重复以上操作
spotify_else['in_deezer_playlists'] = spotify_else['in_deezer_playlists'].str.replace(',', '')
spotify_else['in_deezer_playlists'] = pd.to_numeric(spotify_else['in_deezer_playlists'])

# 'in_shazam_charts'有缺失值
# spotify_else['in_shazam_charts'] = pd.to_numeric(spotify_else['in_shazam_charts']).fillna(0).asype(int)
# 遇到上述相同类型报错
# 重复以上操作
spotify_else['in_shazam_charts'] = spotify_else['in_shazam_charts'].str.replace(',', '')
spotify_else['in_shazam_charts'] = pd.to_numeric(spotify_else['in_shazam_charts']).fillna(0).astype(int)
# 如果不附加.astype(int)会导致处理结果为浮点数

In [24]:
# 查看处理完毕的数据集的前5行
spotify_else.head()

,track_name,artist(s)_name,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,track_id,date
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",553,147,0.038170,43,263,45,10,826,0,2023-07-14
1,LALA,Myke Towers,1474,48,0.036101,48,126,58,14,382,1,2023-03-23
2,vampire,Olivia Rodrigo,1397,113,0.037798,94,207,91,14,949,2,2023-06-30
3,Cruel Summer,Taylor Swift,7858,100,0.216215,116,207,125,12,548,3,2019-08-23
4,WHERE SHE GOES,Bad Bunny,3133,50,0.081869,84,133,87,15,425,4,2023-05-18

In [25]:
# 存储处理完毕的用于其他分析的数据集
spotify_else.to_csv('spotify_else.csv', index= False)